// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"NatsunaBlog/app/model/internal"
)

// DBBLOGONNAV is the golang structure for table DB_BLOG_ONNAV.
type DBBLOGONNAV internal.DBBLOGONNAV

// Fill with you ideas below.
