// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"NatsunaBlog/app/model/internal"
)

// DBBLOGCOMMENT is the golang structure for table DB_BLOG_COMMENT.
type DBBLOGCOMMENT internal.DBBLOGCOMMENT

// Fill with you ideas below.
