// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"NatsunaBlog/app/model/internal"
)

// SqliteSequence is the golang structure for table sqlite_sequence.
type SqliteSequence internal.SqliteSequence

// Fill with you ideas below.
