// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"backend/app/dao/internal"
)

// internalDBBLOGCONFIGDao is internal type for wrapping internal DAO implements.
type internalDBBLOGCONFIGDao = *internal.DBBLOGCONFIGDao

// dBBLOGCONFIGDao is the data access object for table DB_BLOG_CONFIG.
// You can define custom methods on it to extend its functionality as you wish.
type dBBLOGCONFIGDao struct {
	internalDBBLOGCONFIGDao
}

var (
	// DBBLOGCONFIG is globally public accessible object for table DB_BLOG_CONFIG operations.
	DBBLOGCONFIG = dBBLOGCONFIGDao{
		internal.NewDBBLOGCONFIGDao(),
	}
)

// Fill with you ideas below.
