// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"blog/app/dao/internal"
)

// dbBlogConfigDao is the data access object for the table DB_BLOG_CONFIG.
// You can define custom methods on it to extend its functionality as needed.
type dbBlogConfigDao struct {
	*internal.DbBlogConfigDao
}

var (
	// DbBlogConfig is a globally accessible object for table DB_BLOG_CONFIG operations.
	DbBlogConfig = dbBlogConfigDao{internal.NewDbBlogConfigDao()}
)

// Add your custom methods and functionality below.
