// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"blog/app/dao/internal"
)

// dbBlogPostDao is the data access object for the table DB_BLOG_POST.
// You can define custom methods on it to extend its functionality as needed.
type dbBlogPostDao struct {
	*internal.DbBlogPostDao
}

var (
	// DbBlogPost is a globally accessible object for table DB_BLOG_POST operations.
	DbBlogPost = dbBlogPostDao{internal.NewDbBlogPostDao()}
)

// Add your custom methods and functionality below.
