// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"backend/app/dao/internal"
)

// internalDBBLOGPOSTDao is internal type for wrapping internal DAO implements.
type internalDBBLOGPOSTDao = *internal.DBBLOGPOSTDao

// dBBLOGPOSTDao is the data access object for table DB_BLOG_POST.
// You can define custom methods on it to extend its functionality as you wish.
type dBBLOGPOSTDao struct {
	internalDBBLOGPOSTDao
}

var (
	// DBBLOGPOST is globally public accessible object for table DB_BLOG_POST operations.
	DBBLOGPOST = dBBLOGPOSTDao{
		internal.NewDBBLOGPOSTDao(),
	}
)

// Fill with you ideas below.
