// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// DBBLOGPOST is the golang structure of table DB_BLOG_POST for DAO operations like Where/Data.
type DBBLOGPOST struct {
	g.Meta     `orm:"table:DB_BLOG_POST, do:true"`
	ID         interface{} //
	TITLE      interface{} //
	TIMELINE   interface{} //
	TIME       interface{} //
	AUTHOR     interface{} //
	HID        interface{} //
	CONTENT    interface{} //
	CLASSIFY   interface{} //
	TAG        interface{} //
	VISITTIMES interface{} //
	ONTOP      interface{} //
}
