// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// DBBLOGCONFIG is the golang structure of table DB_BLOG_CONFIG for DAO operations like Where/Data.
type DBBLOGCONFIG struct {
	g.Meta   `orm:"table:DB_BLOG_CONFIG, do:true"`
	USERNAME interface{} //
	PASSWORD interface{} //
}
