// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// DBBLOGCONFIG is the golang structure for table DB_BLOG_CONFIG.
type DBBLOGCONFIG struct {
	Username string `orm:"username" json:"username"` //
	Password string `orm:"password" json:"password"` //
}
