// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// DBBLOGCONFIG is the golang structure for table DB_BLOG_CONFIG.
type DBBLOGCONFIG struct {
	Username string `orm:"username" json:"username"` //
	Password string `orm:"password" json:"password"` //
	Title    string `orm:"title"    json:"title"`    //
	Desp     string `orm:"desp"     json:"desp"`     //
	Tag      string `orm:"tag"      json:"tag"`      //
	Url      string `orm:"url"      json:"url"`      //
	Picurl   string `orm:"picurl"   json:"picurl"`   //
}
