// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// DBBLOGONNAV is the golang structure for table DB_BLOG_ONNAV.
type DBBLOGONNAV struct {
	Id     int    `orm:"id"     json:"id"`     //
	Name   string `orm:"name"   json:"name"`   //
	Blogid int    `orm:"blogid" json:"blogid"` //
}
