// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// SqliteSequence is the golang structure for table sqlite_sequence.
type SqliteSequence struct {
	Name string `orm:"name" json:"name"` //
	Seq  string `orm:"seq"  json:"seq"`  //
}
