[server]
	Address = ":8199"
	LogPath = "./log/server"
	LogStdout = false
	ErrorStack = true
	ErrorLogEnabled = true
	ErrorLogPattern = "error.{Ymd}.log"
	AccessLogEnabled = true
	AccessLogPattern = "access.{Ymd}.log"

[database]
	[database.logger]
		path   = "./log/sql"
		level  = "all"
		stdout = true
	[database.default]
		link = "mysql:root:VanillA5Caa@tcp(127.0.0.1:3306)/DB_BLOG"
		debug = true

[gfcli]
	[[gfcli.gen.dao]]
		link = "mysql:root:VanillA5Caa@tcp(127.0.0.1:3306)/DB_BLOG"
		jsonCase = "Snake"