CREATE TABLE DB_BLOG_POST(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TITLE VARCHAR(100) NOT NULL,
    TIMELINE DATETIME DEFAULT (strftime('%Y%m','now')),
    TIME DATETIME DEFAULT (strftime('%Y-%m-%d %H:%M','now')),
    AUTHOR VARCHAR(100) NOT NULL,
    HIDED BOOLEAN NOT NULL,
    CONTENT TEXT,
    CLASSIFY VARCHAR(100) DEFAULT "default",
    TAG TEXT,
    VISIT_TIMES INTEGER NOT NULL,
    ONTOP BOOLEAN NOT NULL,
    LIKE INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE DB_BLOG_CONFIG(
    USERNAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL
);
CREATE TABLE DB_BLOG_ONNAV(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(100) NOT NULL,
    BLOGID INTEGER NOT NULL
);