USE db_blog;
SET global time_zone = '+8:00';

CREATE TABLE DB_BLOG_POST(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(100) NOT NULL,
    TIMELINE VARCHAR(10) DEFAULT DATE_FORMAT(NOW(),'%Y%m'),
    TIME VARCHAR(20) DEFAULT DATE_FORMAT(NOW(),'%Y-%m-%d %H:%i'),
    AUTHOR VARCHAR(100) NOT NULL,
    HID INTEGER NOT NULL DEFAULT 0,
    CONTENT TEXT,
    CLASSIFY VARCHAR(100) NOT NULL DEFAULT "未分类",
    TAG TEXT,
    VISIT_TIMES INTEGER NOT NULL,
    ONTOP INTEGER NOT NULL DEFAULT 2
);
CREATE TABLE DB_BLOG_CONFIG(
    USERNAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL
);
