// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"NatsunaBlog/app/dao/internal"
)

// dBBLOGONNAVDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type dBBLOGONNAVDao struct {
	internal.DBBLOGONNAVDao
}

var (
	// DBBLOGONNAV is globally public accessible object for table DB_BLOG_ONNAV operations.
	DBBLOGONNAV = dBBLOGONNAVDao{
		internal.DBBLOGONNAV,
	}
)

// Fill with you ideas below.
