// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// DBBLOGCONFIG is the golang structure for table DB_BLOG_CONFIG.
type DBBLOGCONFIG struct {
	USERNAME string `orm:"USERNAME" json:"username"` //
	PASSWORD string `orm:"PASSWORD" json:"password"` //
}
