// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// DBBLOGPOST is the golang structure for table DB_BLOG_POST.
type DBBLOGPOST struct {
	ID         int    `orm:"ID,primary"  json:"id"`          //
	TITLE      string `orm:"TITLE"       json:"title"`       //
	TIMELINE   string `orm:"TIMELINE"    json:"timeline"`    //
	TIME       string `orm:"TIME"        json:"time"`        //
	AUTHOR     string `orm:"AUTHOR"      json:"author"`      //
	HID        int    `orm:"HID"         json:"hid"`         //
	CONTENT    string `orm:"CONTENT"     json:"content"`     //
	CLASSIFY   string `orm:"CLASSIFY"    json:"classify"`    //
	TAG        string `orm:"TAG"         json:"tag"`         //
	VISITTIMES int    `orm:"VISIT_TIMES" json:"visit_times"` //
	ONTOP      int    `orm:"ONTOP"       json:"ontop"`       //
}
