// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// DBBLOGCONFIG is the golang structure for table DB_BLOG_CONFIG.
type DBBLOGCONFIG struct {
	USERNAME string `json:"username" ` //
	PASSWORD string `json:"password" ` //
}
