// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// DBBLOGPOST is the golang structure for table DB_BLOG_POST.
type DBBLOGPOST struct {
	ID         int    `json:"id"          ` //
	TITLE      string `json:"title"       ` //
	TIMELINE   string `json:"timeline"    ` //
	TIME       string `json:"time"        ` //
	AUTHOR     string `json:"author"      ` //
	HID        int    `json:"hid"         ` //
	CONTENT    string `json:"content"     ` //
	CLASSIFY   string `json:"classify"    ` //
	TAG        string `json:"tag"         ` //
	VISITTIMES int    `json:"visit_times" ` //
	ONTOP      int    `json:"ontop"       ` //
}
