// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"NatsunaBlog/app/model/internal"
)

// DBBLOGCONFIG is the golang structure for table DB_BLOG_CONFIG.
type DBBLOGCONFIG internal.DBBLOGCONFIG

// Fill with you ideas below.
